name: Blah

on: [push, pull_request, pull_request_target]

jobs:
  job1:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - run: exit 1
      - run: gradle --version
      - run: which gradle
