name: Blah

on: [push, pull_request, pull_request_target]

jobs:
  job1:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: dwieeb/get-changed-files@main
        if: github.event_name != 'push' || github.event.before != '0000000000000000000000000000000000000000'
        with:
          format: 'json'
      - run: echo ${{ steps.files.outputs.all }}
