name: Blah

on: [push, pull_request, pull_request_target]

jobs:
  job1:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: echo $PAYLOAD
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      - id: files
        uses: dwieeb/get-changed-files@main
        with:
          format: 'json'
      - run: echo ${{ steps.files.outputs.all }}
